//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeCutter.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeCutter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 YoutubeCutter 的當地語系化字串。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap BackwardToStartIcon {
            get {
                object obj = ResourceManager.GetObject("BackwardToStartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Duration: 的當地語系化字串。
        /// </summary>
        public static string ClipItemDuration {
            get {
                return ResourceManager.GetString("ClipItemDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End time longer than video length 的當地語系化字串。
        /// </summary>
        public static string ClipItemEndLongerThanVideo {
            get {
                return ResourceManager.GetString("ClipItemEndLongerThanVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End time is earlier than Start time 的當地語系化字串。
        /// </summary>
        public static string ClipItemEndTimeEarlier {
            get {
                return ResourceManager.GetString("ClipItemEndTimeEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This file already exists 的當地語系化字串。
        /// </summary>
        public static string ClipItemFileAlreadyExists {
            get {
                return ResourceManager.GetString("ClipItemFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filename is already taken 的當地語系化字串。
        /// </summary>
        public static string ClipItemFileNameTaken {
            get {
                return ResourceManager.GetString("ClipItemFileNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filename cannot contain 的當地語系化字串。
        /// </summary>
        public static string ClipItemIllegalCharacter {
            get {
                return ResourceManager.GetString("ClipItemIllegalCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clip Length is 0 second 的當地語系化字串。
        /// </summary>
        public static string ClipItemZeroLength {
            get {
                return ResourceManager.GetString("ClipItemZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap CloseButtonIcon {
            get {
                object obj = ResourceManager.GetObject("CloseButtonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Directory: 的當地語系化字串。
        /// </summary>
        public static string DownloadPageDirectory {
            get {
                return ResourceManager.GetString("DownloadPageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        public static string DownloadPageDone {
            get {
                return ResourceManager.GetString("DownloadPageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duration: 的當地語系化字串。
        /// </summary>
        public static string DownloadPageDuration {
            get {
                return ResourceManager.GetString("DownloadPageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open 的當地語系化字串。
        /// </summary>
        public static string DownloadPageOpen {
            get {
                return ResourceManager.GetString("DownloadPageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Queue 的當地語系化字串。
        /// </summary>
        public static string DownloadPageQueue {
            get {
                return ResourceManager.GetString("DownloadPageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Queuing... 的當地語系化字串。
        /// </summary>
        public static string DownloadPageQueuing {
            get {
                return ResourceManager.GetString("DownloadPageQueuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time: 的當地語系化字串。
        /// </summary>
        public static string DownloadPageTime {
            get {
                return ResourceManager.GetString("DownloadPageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sample Orders 的當地語系化字串。
        /// </summary>
        public static string DownloadsListDescription {
            get {
                return ResourceManager.GetString("DownloadsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloads 的當地語系化字串。
        /// </summary>
        public static string DownloadsPageTitle {
            get {
                return ResourceManager.GetString("DownloadsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *You must have ffmpeg.exe for this program to work. 的當地語系化字串。
        /// </summary>
        public static string FFmpegPathWarning {
            get {
                return ResourceManager.GetString("FFmpegPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap ForwardToEndIcon {
            get {
                object obj = ResourceManager.GetObject("ForwardToEndIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 instructions 的當地語系化字串。
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If you encounter bugs, or have suggestions of improvements, you can open an issue at the  的當地語系化字串。
        /// </summary>
        public static string MainPageBugsFirstHalf {
            get {
                return ResourceManager.GetString("MainPageBugsFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 . 的當地語系化字串。
        /// </summary>
        public static string MainPageBugsSecondHalf {
            get {
                return ResourceManager.GetString("MainPageBugsSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 github repository 的當地語系化字串。
        /// </summary>
        public static string MainPageGitHubRepository {
            get {
                return ResourceManager.GetString("MainPageGitHubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 youtube-dl supports downloading youtube videos, however it does not support downloading clips. There are some post-process arguements that allows it, however youtube-dl.exe still downloads the whole video first, then cut out the clips. Which means if you only need 10 seconds of content from a video that is 8 hours long, youtube-dl.exe will download the whole video still. This program essentially grabs the information needed to download the video, then feed it into ffmpeg.exe, which is able to download only  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string MainPagePurpose {
            get {
                return ResourceManager.GetString("MainPagePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The purpose of this program: 的當地語系化字串。
        /// </summary>
        public static string MainPagePurposeTitle {
            get {
                return ResourceManager.GetString("MainPagePurposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Main Page 的當地語系化字串。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to setting, set your youtube-dl.exe and ffmpeg.exe, then the program is ready to use. 的當地語系化字串。
        /// </summary>
        public static string MainPageUsage {
            get {
                return ResourceManager.GetString("MainPageUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Usage: 的當地語系化字串。
        /// </summary>
        public static string MainPageUsageTitle {
            get {
                return ResourceManager.GetString("MainPageUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 . 的當地語系化字串。
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Browse 的當地語系化字串。
        /// </summary>
        public static string SettingsBrowse {
            get {
                return ResourceManager.GetString("SettingsBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Categorize by channel 的當地語系化字串。
        /// </summary>
        public static string SettingsCategorizeByChannel {
            get {
                return ResourceManager.GetString("SettingsCategorizeByChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Categorize by date 的當地語系化字串。
        /// </summary>
        public static string SettingsCategorizeByDate {
            get {
                return ResourceManager.GetString("SettingsCategorizeByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Categorize by video 的當地語系化字串。
        /// </summary>
        public static string SettingsCategorizeByVideo {
            get {
                return ResourceManager.GetString("SettingsCategorizeByVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel\ 的當地語系化字串。
        /// </summary>
        public static string SettingsChannelName {
            get {
                return ResourceManager.GetString("SettingsChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 clip.mp4 的當地語系化字串。
        /// </summary>
        public static string SettingsClipName {
            get {
                return ResourceManager.GetString("SettingsClipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Format:  DownloadPath\ 的當地語系化字串。
        /// </summary>
        public static string SettingsDownloadBaseFormat {
            get {
                return ResourceManager.GetString("SettingsDownloadBaseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Location 的當地語系化字串。
        /// </summary>
        public static string SettingsDownloadLocation {
            get {
                return ResourceManager.GetString("SettingsDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If a title or channel are made only of these characters, they&apos;ll be placed in a folder called Untitled. 的當地語系化字串。
        /// </summary>
        public static string SettingsEmptyFileNameWarning {
            get {
                return ResourceManager.GetString("SettingsEmptyFileNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Note: Since windows doesn&apos;t allow filenames to contain \ / : * ? &quot;&gt; &lt; or |, these characters will be emitted. 的當地語系化字串。
        /// </summary>
        public static string SettingsIllegalCharacterWarning {
            get {
                return ResourceManager.GetString("SettingsIllegalCharacterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings page placeholder text.  Your app description goes here. 的當地語系化字串。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose Theme 的當地語系化字串。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location of ffmpeg.exe 的當地語系化字串。
        /// </summary>
        public static string SettingsPageFfmpegPath {
            get {
                return ResourceManager.GetString("SettingsPageFfmpegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Font Size 的當地語系化字串。
        /// </summary>
        public static string SettingsPageFontSize {
            get {
                return ResourceManager.GetString("SettingsPageFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personalization 的當地語系化字串。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dark 的當地語系化字串。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Light 的當地語系化字串。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youtube Login (Skips ads on YouTube Premium) 的當地語系化字串。
        /// </summary>
        public static string SettingsPageYoutube {
            get {
                return ResourceManager.GetString("SettingsPageYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location of youtube-dl.exe 的當地語系化字串。
        /// </summary>
        public static string SettingsPageYoutubeDLPath {
            get {
                return ResourceManager.GetString("SettingsPageYoutubeDLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verifying, Please wait... 的當地語系化字串。
        /// </summary>
        public static string SettingsVerifying {
            get {
                return ResourceManager.GetString("SettingsVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Video\ 的當地語系化字串。
        /// </summary>
        public static string SettingsVideoTitle {
            get {
                return ResourceManager.GetString("SettingsVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add a download 的當地語系化字串。
        /// </summary>
        public static string ShellAddNewDownload {
            get {
                return ResourceManager.GetString("ShellAddNewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloads 的當地語系化字串。
        /// </summary>
        public static string ShellDownloadsPage {
            get {
                return ResourceManager.GetString("ShellDownloadsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go back 的當地語系化字串。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open or close navigation 的當地語系化字串。
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Main 的當地語系化字串。
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add More Clip 的當地語系化字串。
        /// </summary>
        public static string VideoPageAddMoreClip {
            get {
                return ResourceManager.GetString("VideoPageAddMoreClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string VideoPageCancel {
            get {
                return ResourceManager.GetString("VideoPageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        public static string VideoPageDownload {
            get {
                return ResourceManager.GetString("VideoPageDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End: 的當地語系化字串。
        /// </summary>
        public static string VideoPageEndTime {
            get {
                return ResourceManager.GetString("VideoPageEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Filename 的當地語系化字串。
        /// </summary>
        public static string VideoPageFileName {
            get {
                return ResourceManager.GetString("VideoPageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preparing video... 的當地語系化字串。
        /// </summary>
        public static string VideoPagePreparingVideo {
            get {
                return ResourceManager.GetString("VideoPagePreparingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start: 的當地語系化字串。
        /// </summary>
        public static string VideoPageStartTime {
            get {
                return ResourceManager.GetString("VideoPageStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap YoutubeChannelDefaultIcon {
            get {
                object obj = ResourceManager.GetObject("YoutubeChannelDefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 *You must have youtube-dl.exe for this program to work.  的當地語系化字串。
        /// </summary>
        public static string YoutubeDLPathWarning {
            get {
                return ResourceManager.GetString("YoutubeDLPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap YoutubeVideoDefaultIcon {
            get {
                object obj = ResourceManager.GetObject("YoutubeVideoDefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
